[package]
name = "library"
version = "0.1.0"
authors = ["Nick Linker <nlinker@gmail.com>"]
keywords = ["starcraft", "broodwar", "api", "binding", "ffi"]
repository = "https://github.com/RnDome/bwapi-rs"
description = "FFI bindings to the C++ BWAPI library"
license = "Unlicense/MIT"
build = "build.rs"
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
cxx = "1.0"
once_cell = "1.7.2"
thin_trait_object = "1.1.2"
enum-iterator = "0.6.0"
#derive_builder = "0.10.2"
typed-builder = "0.9.0"
#strum = "0.20"
#strum_macros = "0.20"

[build-dependencies]
cxx-build = "1.0"
#cmake = "0.1"
#cc = "1.0"
#cargo-make = "0.32"
