[package]
name = "library"
version = "0.1.0"
authors = ["Nick Linker <nlinker@gmail.com>"]
keywords = ["starcraft", "broodwar", "api", "binding", "ffi"]
repository = "https://github.com/RnDome/bwapi-rs"
description = "FFI bindings to the C++ BWAPI library"
license = "Unlicense/MIT"
build = "build.rs"
edition = "2018"

## temporary, better to make it (default) rlib
[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
cxx = "1.0.43"
once_cell = "1.7.2"

[build-dependencies]
cxx-build = "1.0.43"
#cmake = "0.1"
#cc = "1.0"
#cargo-make = "0.32"
