[package]
name = "library"
version = "0.1.0"
authors = ["Nick Linker <nlinker@gmail.com>"]
keywords = ["starcraft", "broodwar", "api", "binding", "ffi"]
repository = "https://github.com/RnDome/bwapi-rs"
description = "FFI bindings to the C++ BWAPI library"
license = "Unlicense/MIT"
build = "build.rs"
edition = "2018"

[dependencies]
once_cell = "1.7.2"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
#cmake = "0.1"
#cc = "1.0"
#cargo-make = "0.32"

#[lib]
#crate-type = ["dylib"]
